name: Ubuntu

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      # You might want to Checkout your repo first, but not mandatory
      - uses: actions/checkout@v3
      # Cleanup The Actions Workspace Using Custom Composite Run Actions
      - uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: "*"
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Generate Tmate Session
        run: |
          sudo apt install tmate
          sudo bash tmate.sh | tee /tmp/ssh.txt
          cat /tmp/ssh.txt

      - name: Blank Output
        run: |
          bash blank.sh
